// data.ts (Pakistan-ready - React Native compatible)
// Plain TypeScript data module — works unchanged in React Native.
// Import into your screens like:
//   import { pets, popularBreeds, breeds, statesWithDogCities } from "./data";

export const pets = [
  {
    id: 1,
    name: "Rio",
    img: "https://images.unsplash.com/photo-1612831662375-295c1003d3db",
    breed: "Labrador Retriever",
    gender: "Male",
    age: 2,
    city: "Karachi",
    price: 450000,
  },
  {
    id: 2,
    name: "Bella",
    img: "https://images.unsplash.com/photo-1558788353-f76d92427f16",
    breed: "Golden Retriever",
    gender: "Female",
    age: 3,
    city: "Lahore",
    price: 520000,
  },
  {
    id: 3,
    name: "Max",
    img: "https://images.unsplash.com/photo-1507149833265-60c372daea22",
    breed: "Beagle",
    gender: "Male",
    age: 2,
    city: "Islamabad",
    price: 380000,
  },
  {
    id: 4,
    name: "Lucy",
    img: "https://images.unsplash.com/photo-1593134257781-3cc0d8a25f90",
    breed: "Shih Tzu",
    gender: "Female",
    age: 2,
    city: "Rawalpindi",
    price: 400000,
  },
  {
    id: 5,
    name: "Rocky",
    img: "https://images.unsplash.com/photo-1543466835-00a7907e9de1",
    breed: "Siberian Husky",
    gender: "Male",
    age: 3,
    city: "Peshawar",
    price: 600000,
  },
  {
    id: 6,
    name: "Milo",
    img: "https://images.unsplash.com/photo-1619983081563-430f636027b4",
    breed: "German Shepherd",
    gender: "Male",
    age: 3,
    city: "Multan",
    price: 550000,
  },
  {
    id: 7,
    name: "Luna",
    img: "https://images.unsplash.com/photo-1517849845537-4d257902454a",
    breed: "Poodle",
    gender: "Female",
    age: 2,
    city: "Faisalabad",
    price: 420000,
  },
  {
    id: 8,
    name: "Simba",
    img: "https://images.unsplash.com/photo-1616443104899-6c3b7b0de9ef",
    breed: "Rottweiler",
    gender: "Male",
    age: 2,
    city: "Quetta",
    price: 500000,
  },
  {
    id: 9,
    name: "Zoe",
    img: "https://images.unsplash.com/photo-1601758064221-0c3b3e5084d3",
    breed: "Pomeranian",
    gender: "Female",
    age: 2,
    city: "Hyderabad",
    price: 350000,
  },
  {
    id: 10,
    name: "Teddy",
    img: "https://images.unsplash.com/photo-1507149833265-60c372daea22",
    breed: "Chow Chow",
    gender: "Male",
    age: 3,
    city: "Gujranwala",
    price: 580000,
  },
];

export const popularBreeds = [
  "Labrador Retriever",
  "German Shepherd",
  "Golden Retriever",
  "Pomeranian",
  "Beagle",
  "Siberian Husky",
  "Bulldog",
  "Pug",
  "Rottweiler",
  "Poodle",
  "Doberman",
  "Shih Tzu",
];

export const breeds = [
  "Breed",
  "Labrador Retriever",
  "Golden Retriever",
  "German Shepherd",
  "Pug",
  "Beagle",
  "Bulldog",
  "Rottweiler",
  "Poodle",
  "Siberian Husky",
  "Doberman",
  "Shih Tzu",
  "Chow Chow",
];

// Note: Matched variable name to match the import referenced in your screen (`statesWithDogCities`)
export const statesWithDogCities: Record<string, string[]> = {
  Punjab: [
    "Lahore",
    "Faisalabad",
    "Rawalpindi",
    "Multan",
    "Gujranwala",
    "Sialkot",
    "Sargodha",
    "Bahawalpur",
  ],
  Sindh: [
    "Karachi",
    "Hyderabad",
    "Sukkur",
    "Larkana",
    "Nawabshah",
    "Mirpurkhas",
  ],
  "Khyber Pakhtunkhwa": [
    "Peshawar",
    "Mardan",
    "Abbottabad",
    "Swabi",
    "Kohat",
    "Bannu",
  ],
  Balochistan: ["Quetta", "Gwadar", "Turbat", "Khuzdar", "Zhob"],
  "Islamabad Capital Territory": ["Islamabad"],
  "Gilgit-Baltistan": ["Gilgit", "Skardu"],
  "Azad Jammu & Kashmir": ["Muzaffarabad", "Mirpur", "Kotli"],
};